### ISSUE TITLE
resetting after working on alignment

### ISSUE THREAD

**Issue by hannalotte** [digling/edictor#117]
Dear makers of Edictor,

I worked quite a bit with Edictor lately and very much appreciate what it does. However, there is one annoying thing I noticed. I'm using the word list viwe to asign cognate classes to words, then I right click on the ID number of the cognate class and can correct the alignment there. After submitting the changes, everything will be reset. This means I have to select my languages, concepts, columns, and other settings from skretch. Is there anything to do about it?

I hope it is clear what I mean, otherwise pleasee let me know and I can clarify the problem in more detail.

Best regards,
Hanna
(Leiden University)

**Comment by LinguList** [comment]
Dear Hanna, unfortunately, I do not yet quite get it, so could you ideally submit one or two or more screenshots of what happens? You can paste them directly into the field in github issues, which is quite convenient, and in this way, I'll see clearly what the problem is and what I can do...

**Comment by hannalotte** [comment]
![afbeelding](https://cloud.githubusercontent.com/assets/22792492/25844724/b5a8c54a-34ab-11e7-9120-419f0ee75e77.png)

**Comment by hannalotte** [comment]
![afbeelding](https://cloud.githubusercontent.com/assets/22792492/25844827/0a0cdb8a-34ac-11e7-961d-d3f49c05962a.png)

Then I right click on a cogante ID (here 1670) and get to the alignment editing function.

**Comment by hannalotte** [comment]
![afbeelding](https://cloud.githubusercontent.com/assets/22792492/25844912/48a339d4-34ac-11e7-9ff6-1a75330205d9.png)
 After submitting aliignment changes here, all selection previously made are reset. In the screen shot you can see that all languages are selected, although before I had selected a subset.

**Comment by LinguList** [comment]
Thanks! I'll try to replicate this on my system, and once confirmed will see what I can do. 

Your Machine is a MAC or a Windows or a Linux? Some bugs only occur on one platform. And I assume you are using Firefox, right?

**Comment by hannalotte** [comment]
Hope this is more clear now. I guess this is mainly a problem because the dataset has such a large number of doculects. Yes, I am using firefox on WIndows.

**Comment by hannalotte** [comment]
Thanks for your reply and looking forward to hear more!

**Comment by LinguList** [comment]
It is clear, will try to see whether it always occurs or size is a problem...

**Comment by LinguList** [comment]
Just confirmed the bug, and it is a general pattern: if you only annotate cognates WITHIN a group, this is fine, but once you do the alignments, it will 

1 give you all alignments for that cognate set
2 reset to normal mode afterwards

I understand the bug, but I wonder how this is best addressed.

So far, given that I know that you people from Leiden work on languages in the range of 100+, I wonder if it is the right way to do cognate judgments for all of those anyway. It is extremely difficult to keep track of what is going on, and I personally would rather work on subsets in smaller files, finalize those, and then add another kind of columns for overarching cognate sets. Also for the alignments, it may be better then to automatize those and not do it for the whole bunch. Remmeber IDs are always traced and unless you remove or add a new ID (which is possible), you should be fine by separating data into small sets, working on those, and then thinking of how to combine later for the bigger picture. Even alignments do not make sense if applied to a deeper level, as too much morphology is going on, so the signal left will be really small.

I'll now quickly look into the code to see if the bug can be fixed quickly, but conceptually, if we work on a subset and want to update the alignment while having the WHOLE data in the file, we need to do the full alignments anyway. So I wonder if fixing this bug is actually something we want to do conceptually, as making alignments for four languages would anyway require re-editing the whole bunch of words in one cognate set.

I'd like you, @hannalotte, to think a bit about this:

* how important are the alignments for you? Could you consider doing the cognates on a shallow level only, by splitting the data, and later on merge the whole stuff (the automatic alignment algos in Python, not the edictor, are quite developed and work well, so little correction is usually needed, unless the data is just extremely remotely cognate, with many different morphemes in compounds messing up the picture)

Before I go into action here, I need to find a good solution for this conceptual question. I tend towards working on subfamilies and then maybe using intermediate reconstructions in a next step to group on deeper levels. Any ideas or suggestions are welcome.

**Comment by Anaphory** [comment]
This issue actually comes from us trying to do intermediate reconstructions, and not really having the appropriate tools to do that in a reasonable manner from the wordlist data we have. It does feel somewhat like we are abusing adictor for a task it is not designed for. Suggestions are welcome.

Currently our plan was to manually improve similarity codings and alignments for a dialect-chain-plus-nearest-neighbor subset (Keraf's word lists of the Lamaholot chain plus neighbors, plus our own material for those languages, which is more extensive) of all our languages, and then find systematic sound correspondences within the alignments so we can reconstruct, starting with proto-Lamaholot.

I guess I could split the data into separate files. One problem with that approach is that it will make working with numerical COGIDs more difficult – when splitting a currently postulated cognate class just from a subset of the list may generate a COGID that is already used only in the other part of the list; but on the other hand, we do not want to explicitly forbid cross-semantic (hand/arm/five) cognate sets between the two language-subsets. This problem made us decide to always use the whole data set originally.

**Comment by LinguList** [comment]
That's why I would use two different cogids for the subgroup, right? Your file will have two IDs, like "deepid", and "youngid" (you can change in the settings which one is the one you pull for doing alignments, even within one session, as well as the column where you put alignments, so two alignments are possible, etc. I'd do it like that, or, say, we will do it like that in my project on Sino-Tibetan...

**Comment by Anaphory** [comment]
Ah, right. That makes some sense. I'll have a look how to make that work with my scripts, but it sounds feasible.

**Comment by LinguList** [comment]
IN terms of LingPy, you'll just tweak the "ref" object which is always
denoted for the column where you write the cognate set identifier, and
the "alignments" keyword, which writes the alignments to the file into
the column name as specified by the keywords...

**Comment by hannalotte** [comment]
Thanks, Gereon and Mattis, to follow up on this! I will leave the discussion to the two of you because I am not familiar enough with the technical details ... But if you need further input form me, let me know!

**Comment by LinguList** [comment]
A general problem in this issue is that the alignments should not cause
a re-setting once submitted. The problem of showing all alignments even
if jus ta subset is selected is a design features, as we should not add
only one alignment for four taxa if the full set of taxa is 20 etc. So
this issue will stay open until the submission of alignments does no
longer reset (which is just a lazyness from my side, as I'll need to add
some more code on this point).

**Comment by LinguList** [comment]
Just found that changing this line here:

```
  resetFormat(CFG['formatter']);
  createSelectors();
  applyFilter();
```

into this line:

```
  resetFormat(CFG['formatter']);
  //createSelectors();
  applyFilter();
```

that is, uncommenting the ```createSelectors()``` function does the trick of not resetting. I do not remember why I introduced it, but I'll update this preliminarily now. Please inform me, however, on any bad side effects of this. Ideally, I should change the createSelectors-function.
