### ISSUE TITLE
Edictor to NEXUS

### ISSUE THREAD

**Issue by thiagochacon** [digling/edictor#124]
I suggest one to create a way to convert an edictor type of file to a NEXUS format file, having at least the following basic elements

doculect / taxa
cogid / characters

and a matrix of languages and alignments, where every site is one cogid.

**Comment by LinguList** [comment]
this should be put into lingpy, as edictor itself does not quality for this, we're handling the issue from there.

**Comment by thiagochacon** [comment]
cool, I just saw this feature in Edictor!

**Comment by LinguList** [comment]
Yes, I know, but if I start adding 5 different nexus output formats, or invest my time doing, say, the proto-language addon, and tell people how to do the specific nexus in Python and LingPy, I think the time is better spent. I consider the feature as a quick way to look at neighbor nets (as the current nexus only works on them). We may add cross-semantic cognates later, but for the time being, I must put it low on my list of priorities, as NEXUS is also a very complex format, since every software is using their own form (incredible, in fact).
