### ISSUE TITLE
Word list preview: Moving between concepts

### ISSUE THREAD

**Issue by seannyD** [digling/edictor#171]
I have a concept with more than 10 entries, and I click the "next" button to view items 11-20. That's fine. But if I then move to the next concept, and that concept has fewer than 11 entries, then I just see a blank list. The item index from getCurrent() is not changing, and it's trying to show me items 11-20 from a list with fewer than 11 items.

Either the call to `showWLS(getCurrent())` should just be `showWLS(1)`, or check whether `start` is greater than the word list length in wordlist.js. e.g. add this:

```
    if(start > WLS["rows"].length){
    	start = 1;
    }
```

To this position:

https://github.com/digling/edictor/blob/9ea59a6c0fdd45a7364d7bee98f36e2cea3b3132/js/wordlist.js#L718

**Comment by seannyD** [comment]
Hmm, this may be the same as issue #132

**Comment by LinguList** [comment]
This issue is easily solved by clicking on the "OK" or (refresh)? 

So as a workaround, when you jump through concepts, you have to then click on START. START is consistent here, since START means: the start of your current selection, and if you jump thorugh edictor by concepts, it means, the concept filter (where you can also trigger this) is modified (check this out). So ideally, we'd find a way to solve this showing empty rows, yes, but for the time being, it can be handled with the start button (which is needed).

**Comment by LinguList** [comment]
Ah, cool, I'll check in the JS if that helps, what you suggest.

**Comment by LinguList** [comment]
The problem here is in any case the mixing of different views: If you have the concept view, you better o to settings and make sure you see 1000 lines always. If you anyway look at concepts, you want to see them all, so setting your view to 5 or 10 doesn't make sense, right? And the mixing of both philosophies clashes and becomes difficult to maintain.  That's also why I never looked into fixing this, since it would not occur upon proper settings (which we handle per project from the URL: see the "customize" panel to check how the things are displayed in URL settings).

**Comment by seannyD** [comment]
OK, this makes sense.

**Comment by LinguList** [comment]
Also handled now with last push, finally, thanks for pushing me, it will enhance for those who work on concepts...
