### ISSUE TITLE
Slash annotation and grouping sounds fails for single-phoneme results

### ISSUE THREAD

**Issue by FredericBlum** [digling/edictor#189]
If one tries to use the slash annotation for a word that consists only of a single phoneme, EDICTOR will automatically separate the entry in the form of `space dot space`. The same happens if one tries to group the only two sounds of a word with a dot.

Previously | Change made | Result
--- | --- | ---
ī | ī/i | ī . i
e ʔ | e.ʔ | e . ʔ

**Comment by LinguList** [comment]
Yes, I have to change the behaviour of the segmentation method here: if 
there's no space in the data, it assumes it should automatically segment 
now. Unfortunately, it is coupled with the highlight feature, so it 
tries it always. To work around this, you can do the following: switch 
off highlight for tokens and alignments in settings. Then do the slash 
etc., for mono-syllables. Then switch it on, but don't touch the tokens 
entry. This would then not do any splitting, since splitting of 
non-space sequences happens only upon inserting them. Apart from this, I 
should separate segmentation and highlighting (highlight means: color 
background). In this way, one could just switch off automatic 
segmentation, given that this is done anyway.

**Comment by LinguList** [comment]
New behavior in edictor3, @blumf: no tokenization is carried out by default. Users must explicitly type a space in front of a sound sequence to trigger segmentation. This is fast, but it also circumvents all problems here, and it is quite intuitive if you want to segment data manually with edictor.
