### ISSUE TITLE
Changing one segment in entry resets all alignments

### ISSUE THREAD

**Issue by Tarotis** [digling/edictor#192]
When changing (adding, modifying, grouping) any segment in the TOKENS column, the whole ALIGNMENT column resets. Maybe this is actually expected behavior but I think it will be good for documentation purposes to have this made explicit. Here is an example:

Old Alignment: - i w i + β i tʃ i
Change: add another segment, so it becomes i w i + β i tʃ i m (tokens)
New Alignment: i w i + β i tʃ i

The problems are thus two-fold: We have the old problem that I need to confirm two times via enter so that the new sound gets added to the alignment correctly. But second, we have to be aware that changing any segment resets all the alignments of an entry. I think that this has actually been a major source of problem in my database.

Imagine editing 200 nasalization symbols, or grouping vowels and glottal stops: Not only does the alignment of the respective root/morpheme get changed in which the symbol is actually changed - but actually all cognate sets of morphemes that are part of the same word. One needs to be aware of this in order to avoid unconsciously resetting the alignments without recreating them. We will now run another round of checks to fix this in our database.

**Comment by LinguList** [comment]
The alignment synchronization with the TOKENS is important, but not trivial. Currently, synchronization has one bug that I did not have the time to fix yet: it does not synchronize if you only press enter. It only synchronizes if you do this a second time. I know myself that this is annoying, but I do not find time to fix the bug, and nobody has so far tried to read the code to help me.

For documentation: please propose documentation items in the form of a README or TUTORIAL file here, or anywhere, so we can link to them. 

For currently living with the bug: I use the arrow up arrow down feature to make sure alignments are synchronized. 

For the general philosophical discussion around what is and what is not annoying when editing data in manual and / or computer-assisted form: it is always a trade-off between boring manual work on the one hand, but freedom to change one's ideas on the other hand, vs. fast computational work with a limited amount of freedom. 

If you follow the school-book procedure of the comparative method, the modification of the nasal symbols is an analysis that you would have done long ago by having a deep understanding of all individual varieties and how the sound changes behave. So we have first segmentation and token representation and then alignments. But since all is done at the same time, alignments, segmentation, resegmentation, modification of individual symbols, alignments, cognate judgments, I would argue that we cannot avoid to have solutions for every problem.

In your case with nasalization symbols, however, we HAVE a choice. And this is something that I though you'd know well already: you can always use pyedictor or lexibase to access and manipulate the data, even within the sqlite file, but you must afterwards upload the data to the server and hope you have not destroyed anything.

**Comment by LinguList** [comment]
For this to be done, you'd have to contact me, we would discuss, what has to be changed, and we'd do so with a python script.
