### ISSUE TITLE
Allow to merge columns when doing the alignments.

### ISSUE THREAD

**Issue by LinguList** [digling/edictor#41]
Merging of columns can be essential when carrying out alignments. Here, there are two ways to proceed:
- merge two or more columns completely by reducing their segmentation [explicit merging], or
- define a column as merged by keep the fine distinctions in the alignment preserved [implicit merging]

Both possibilities should be implemented, since there will be situations in which both are valuable. The question is, however, how implicit merging of columns could be represented? We could use brackets as another separator, like, for example:

```
t [ u o ] x t a
t [ - o ] - t e
```

In combination with ignored columns, this would then look like:

```
r [ i e ] ( t o u )
r [ - e ] ( - - - )
```

It is probably the easiest way right now. Yet it is a bit complicated to adapt the code...

**Comment by LinguList** [comment]
Note that this feature becomes the more important the more I made active tests with language data: Complex columns may be the solution for may otherwise problematic instances, and they will push the accuracy of the correspondence section greatly.

**Comment by tpellard** [comment]
I am just starting playing with edictor but I think that such a feature is indeed needed. Did you make any progress? 
However, there might be severe complications when comparing several languages. Take for example two binary comparisons:
```
L1: k [ w a ] ŋ
L2: k [ - o ] ŋ
```
and
```
L1: k w [ a ŋ ] 
L3: k w [ ã - ]
```
So far so good, but combining the two correspondences requires to add a different pair of braces that crosses the first one:
```
k { w [ a } ŋ ]
k { - [ o } ŋ ]
k { w [ ã } - ]
```
because a single set of braces will not be able to encode the intersection of the two correspondences:
```
k [ w [ a ] ŋ ]
k [ - [ o ] ŋ ]
k [ w [ ã ] - ]
```
Each new language added might require a new set of braces, but obviously there are not enough symbols available.
