### ISSUE TITLE
Improve handling of syllable stress markers

### ISSUE THREAD

**Issue by Anaphory** [digling/edictor#96]
Syllable stress markers are recognized as such and not marked as “unknown symbol”, but are merged with  adjacent phonemes to new phonemes, such that `'toto` will be split into `'t o t o`, and `'t` and `t` will be understood to be two different phonemes.

There may be benefits to keeping track of syllable stress (though IMO this matters more for syllable nulcei, so one option might be to provide lingpy with some way to transfer syllable-initial stress marks to the nucleus), but the phoneme inventory should not distinguish between `'t` and `t`.

**Comment by LinguList** [comment]
In lingpy, I tend to split different kinds of information into a string that stores things like, e.g., stress. From a data-perspective, this would generally make more sense (one could even apply this to all kinds of suprasegmental data). Unfortunately, no linguist would ANNOTATE this data. So for the moment, there should be a pragma that ignores accents, but would, on a broader perspective, also cover ambiguities of IPA. However, this is computationally intensive, as it will be re-created all the time. 

So one intermediate solution might be to try and derive a syllable model for each word from lingpy and annotate the stress in an extra-column, removing it from the edictor-segments-column. In lingpy, this could be done as:

```python
>>> tokens2class('string', 'cv') # convert to cv-structures
```

Then find the index for the accented syllable, and, e.g., convert the CV string to uppercase on accented syllables.

But here's a broader question, relating to an old [lingpy issue](https://github.com/lingpy/lingpy/issues/263) (I just re-filed it, since it was never officially issued). We NEED a way to handle accents, but it is not yet clear what is the optimal approach (within the string? in an extra-column?).

**Comment by LinguList** [comment]
This thread is also related to the cross-linguistic phonetic alphabet:

* https://github.com/glottobank/clpa/issues/20
