### ISSUE TITLE
Alignment window doesn't resize content

### ISSUE THREAD

**Issue by klamermaf** [digling/edictor#99]
![capture](https://cloud.githubusercontent.com/assets/22613544/19340430/26fb6102-9129-11e6-9efa-4a929efe0456.PNG)

To align a long list of cognates, I need a resized window, but only the red background resizes, not the content of the window.

**Comment by LinguList** [comment]
I see, this is a css problem, rather than a software problem, as the
doculect names are as long as I never thought they would be. One could
change this by either making explicit that long doculect strings are not
necessarily recommended (my favorite solution, as linguists usually work
with short cuts), or by adjusting the CSS in the tool, which would be
the class that defines how long these columns for doculect names are on
average.

I understand that having information on classification is useful in some
applications. But instead of putting all in one doculect string, it
seems more useful to add a second "classification" column, in which
users can address their classification of languages to facilitate
sorting in other contexts. This feature, that is, including
classificaiton, would be another issue, and it would require some
discussion as of where it would be useful to have it.

Changing CSS would be simpler, but looking at your doculect names, I'd
suggest to change them to shorter strings, as I think this can be done
without information loss (Timor-Alor-Pantar --> TAP, etc.). In this way,
you can avoid the problem without having to wait for a fix from my side.

**Comment by LinguList** [comment]
just realized this issue could also be fixed by just cutting the long strings, which is already done in the note-field of the EDICTOR. This is an easy fix, but I need to look back into the code and am busy this week, yet it can be handled early next week.

**Comment by Anaphory** [comment]
Yes, our doculect names are long, which is a side-issue of not being able to show and sort by additional columns in the Cognateset-editing pseudowindow.
But in this particular issue, it looks like the white area inside the alignment window should scale, which would *also* fix the issue of overlapping lect names and alignments if alignments were right-aligned and lect names left-aligned. Please don't cut long strings.

**Comment by LinguList** [comment]
just a stupid missing css attribute. In general, all was already there. 
But here is a file to replicate the bug or to check it no longer exists:
[replicate-error.txt](https://github.com/digling/edictor/files/536055/replicate-error.txt)
